class Championss {
  String name;
  String title;
  String release;
  String lastUpdate;
  String classes;
  List<String> legacy;
  String position;
  String resource;
  String rangeType;
  String adaptiveType;
  String storePriceBE;
  String storePriceRP;
  String imageChmp;
  String imageChmpIcn;
  String imageChmp3D;
  String imageClasses;
  List<String> imageLegacy;
  String imagePosition;
  String imageResource;
  String imageRange;

  Championss({
    required this.name,
    required this.title,
    required this.release,
    required this.lastUpdate,
    required this.classes,
    required this.legacy,
    required this.position,
    required this.resource,
    required this.rangeType,
    required this.adaptiveType,
    required this.storePriceBE,
    required this.storePriceRP,
    required this.imageChmp,
    required this.imageChmpIcn,
    required this.imageChmp3D,
    required this.imageClasses,
    required this.imageLegacy,
    required this.imagePosition,
    required this.imageResource,
    required this.imageRange,
  });
}

var listChampion = [
  Championss(
    name: 'Aatrox',
    title: 'The Darkin Blade',
    release: '2013-06-13',
    lastUpdate: 'V14.14',
    classes: 'Juggernaut',
    legacy: ['Fighter', 'Tank'],
    position: 'Top',
    resource: ' Manaless',
    rangeType: 'Melee',
    adaptiveType: 'Physical',
    storePriceBE: '4800',
    storePriceRP: '880',
    imageChmp: 'assets/images/aatrox_banner.png',
    imageChmpIcn: 'assets/images/aatrox_icon.jpg',
    imageChmp3D: 'assets/images/aatrox_3d.png',
    imageClasses: 'assets/images/fighter_icon.png',
    imageLegacy: [
      'assets/images/fighter_icon.png',
      'assets/images/tank_icon.png'
    ],
    imagePosition: 'assets/images/top_icon.png',
    imageResource: 'assets/images/manaless_icon.png',
    imageRange: 'assets/images/melee_icon.png',
  ),
  Championss(
    name: 'Aurelion Sol',
    title: 'The Star Forger',
    release: '2016-03-24',
    lastUpdate: 'V14.15',
    classes: 'Battlemage',
    legacy: ['Mage', 'Mage'],
    position: 'Middle',
    resource: ' Mana',
    rangeType: 'Ranged',
    adaptiveType: 'Magic',
    storePriceBE: '4800',
    storePriceRP: '880',
    imageChmp: 'assets/images/aurelion_sol_banner.png',
    imageChmpIcn: 'assets/images/aurelion_sol_icon.jpg',
    imageChmp3D: 'assets/images/aurelion_sol_3d.png',
    imageClasses: 'assets/images/fighter_icon.png',
    imageLegacy: [
      'assets/images/mage_icon.png',
      'assets/images/mage_icon.png'
    ],
    imagePosition: 'assets/images/mid_icon.png',
    imageResource: 'assets/images/mana_icon.png',
    imageRange: 'assets/images/ranged_icon.png',
  ),
  Championss(
    name: "Cho'Gath",
    title: 'The Terror Of The Void',
    release: '2009-06-26',
    lastUpdate: 'V14.14',
    classes: 'Specialist',
    legacy: ['Tank', 'Mage'],
    position: 'Top',
    resource: ' Mana',
    rangeType: 'Melee',
    adaptiveType: 'Magic',
    storePriceBE: '1350',
    storePriceRP: '585',
    imageChmp: 'assets/images/chogath_banner.png',
    imageChmpIcn: 'assets/images/chogath_icon.jpg',
    imageChmp3D: 'assets/images/chogath_3d.png',
    imageClasses: 'assets/images/specialist_icon.png',
    imageLegacy: [
      'assets/images/tank_icon.png',
      'assets/images/mage_icon.png'
    ],
    imagePosition: 'assets/images/top_icon.png',
    imageResource: 'assets/images/mana_icon.png',
    imageRange: 'assets/images/melee_icon.png',
  ),
  Championss(
    name: 'Fiddlesticks',
    title: 'The Ancient Fear',
    release: '2009-02-21',
    lastUpdate: 'V14.14',
    classes: 'Specialist',
    legacy: ['Mage', 'Support'],
    position: 'Jungle',
    resource: ' Mana',
    rangeType: 'Ranged',
    adaptiveType: 'Magic',
    storePriceBE: '1350',
    storePriceRP: '585',
    imageChmp: 'assets/images/fiddlesticks_banner.png',
    imageChmpIcn: 'assets/images/fiddlesticks_icon.png',
    imageChmp3D: 'assets/images/fiddlesticks_3d.png',
    imageClasses: 'assets/images/specialist_icon.png',
    imageLegacy: [
      'assets/images/mage_icon.png',
      'assets/images/support_legacy.png'
    ],
    imagePosition: 'assets/images/jungle_icon.png',
    imageResource: 'assets/images/mana_icon.png',
    imageRange: 'assets/images/melee_icon.png',
  ),
  Championss(
    name: 'Alistar',
    title: 'The Minotaur',
    release: '2009-02-21',
    lastUpdate: 'V14.16',
    classes: 'Vanguard',
    legacy: ['Tank', 'Support'],
    position: 'Support',
    resource: ' Mana',
    rangeType: 'Melee',
    adaptiveType: 'Magic',
    storePriceBE: '1350',
    storePriceRP: '585',
    imageChmp: 'assets/images/alistar_banner.png',
    imageChmpIcn: 'assets/images/alistar_icon.jpg',
    imageChmp3D: 'assets/images/alistar_3d.png',
    imageClasses: 'assets/images/tank_icon.png',
    imageLegacy: [
      'assets/images/tank_icon.png',
      'assets/images/support_legacy.png'
    ],
    imagePosition: 'assets/images/support_position.png',
    imageResource: 'assets/images/mana_icon.png',
    imageRange: 'assets/images/melee_icon.png',
  ),
  Championss(
    name: 'Amumu',
    title: 'The Sad Mummy',
    release: '2009-06-26',
    lastUpdate: 'V14.9',
    classes: 'Vanguard',
    legacy: ['Tank', 'Support'],
    position: 'Jungle',
    resource: ' Mana',
    rangeType: 'Melee',
    adaptiveType: 'Magic',
    storePriceBE: '450',
    storePriceRP: '260',
    imageChmp: 'assets/images/amumu_banner.png',
    imageChmpIcn: 'assets/images/amumu_icon.jpg',
    imageChmp3D: 'assets/images/amumu_3d.png',
    imageClasses: 'assets/images/tank_icon.png',
    imageLegacy: [
      'assets/images/tank_icon.png',
      'assets/images/support_legacy.png'
    ],
    imagePosition: 'assets/images/jungle_icon.png',
    imageResource: 'assets/images/mana_icon.png',
    imageRange: 'assets/images/melee_icon.png',
  ),
  Championss(
    name: 'Anivia',
    title: 'The Cryophoenix',
    release: '2009-07-10',
    lastUpdate: 'V13.22',
    classes: 'Battlemage',
    legacy: ['Mage', 'Support'],
    position: 'Middle',
    resource: ' Mana',
    rangeType: 'Ranged',
    adaptiveType: 'Magic',
    storePriceBE: '3150',
    storePriceRP: '790',
    imageChmp: 'assets/images/anivia_banner.png',
    imageChmpIcn: 'assets/images/anivia_icon.jpg',
    imageChmp3D: 'assets/images/anivia_3d.png',
    imageClasses: 'assets/images/mage_icon.png',
    imageLegacy: [
      'assets/images/mage_icon.png',
      'assets/images/support_legacy.png'
    ],
    imagePosition: 'assets/images/mid_icon.png',
    imageResource: 'assets/images/manaless_icon.png',
    imageRange: 'assets/images/melee_icon.png',
  ),
  Championss(
    name: 'Bard',
    title: 'The Wandering Caretaker',
    release: '2015-03-12',
    lastUpdate: 'V14.15',
    classes: 'Catcher',
    legacy: ['Support', 'Mage'],
    position: 'Support',
    resource: ' Mana',
    rangeType: 'Ranged',
    adaptiveType: 'Magic',
    storePriceBE: '4800',
    storePriceRP: '880',
    imageChmp: 'assets/images/bard_banner.png',
    imageChmpIcn: 'assets/images/bard_icon.jpg',
    imageChmp3D: 'assets/images/bard_3d.png',
    imageClasses: 'assets/images/support_legacy.png',
    imageLegacy: [
      'assets/images/support_legacy.png',
      'assets/images/mage_icon.png'
    ],
    imagePosition: 'assets/images/support_position.png',
    imageResource: 'assets/images/mana_icon.png',
    imageRange: 'assets/images/ranged_icon.png',
  ),
  Championss(
    name: 'Blitzcrank',
    title: 'The Great Steam Golem',
    release: '2009-09-02',
    lastUpdate: 'V14.13',
    classes: 'Catcher',
    legacy: ['Tank', 'Support'],
    position: 'Support',
    resource: ' Mana',
    rangeType: 'Melee',
    adaptiveType: 'Magic',
    storePriceBE: '1350',
    storePriceRP: '585',
    imageChmp: 'assets/images/blitzcrank_banner.png',
    imageChmpIcn: 'assets/images/blitzcrank_icon.jpg',
    imageChmp3D: 'assets/images/blitzcrank_3d.png',
    imageClasses: 'assets/images/support_legacy.png',
    imageLegacy: [
      'assets/images/tank_icon.png',
      'assets/images/support_legacy.png'
    ],
    imagePosition: 'assets/images/support_position.png',
    imageResource: 'assets/images/mana_icon.png',
    imageRange: 'assets/images/melee_icon.png',
  ),
  Championss(
    name: 'Akshan',
    title: 'The Rogue Sentinel',
    release: '2021-07-22',
    lastUpdate: 'V14.14',
    classes: 'Marksman',
    legacy: ['Marksman', 'Assassin'],
    position: 'Middle',
    resource: ' Mana',
    rangeType: 'Ranged',
    adaptiveType: 'Physical',
    storePriceBE: '4800',
    storePriceRP: '880',
    imageChmp: 'assets/images/akshan_banner.png',
    imageChmpIcn: 'assets/images/akshan_icon.png',
    imageChmp3D: 'assets/images/akshan_3d.png',
    imageClasses: 'assets/images/marksman_icon.png',
    imageLegacy: [
      'assets/images/marksman_icon.png',
      'assets/images/assassin_icon.png'
    ],
    imagePosition: 'assets/images/mid_icon.png',
    imageResource: 'assets/images/mana_icon.png',
    imageRange: 'assets/images/ranged_icon.png',
  ),
  Championss(
    name: 'Hecarim',
    title: 'The Shadow Of War',
    release: '2012-04-18',
    lastUpdate: 'V14.14',
    classes: 'Diver',
    legacy: ['Fighter', 'Tank'],
    position: 'Jungle',
    resource: ' Mana',
    rangeType: 'Melee',
    adaptiveType: 'Physical',
    storePriceBE: '4800',
    storePriceRP: '880',
    imageChmp: 'assets/images/hecarim_banner.png',
    imageChmpIcn: 'assets/images/hecarim_icon.png',
    imageChmp3D: 'assets/images/hecarim_3d.png',
    imageClasses: 'assets/images/fighter_icon.png',
    imageLegacy: [
      'assets/images/fighter_icon.png',
      'assets/images/tank_icon.png'
    ],
    imagePosition: 'assets/images/jungle_icon.png',
    imageResource: 'assets/images/mana_icon.png',
    imageRange: 'assets/images/melee_icon.png',
  ),
  Championss(
    name: 'Thresh',
    title: 'The Chain Warden',
    release: '2013-01-23',
    lastUpdate: 'V14.8',
    classes: 'Catcher',
    legacy: ['Support', 'Tank'],
    position: 'Support',
    resource: 'Mana',
    rangeType: 'Ranged',
    adaptiveType: 'Physical',
    storePriceBE: '3150',
    storePriceRP: '790',
    imageChmp: 'assets/images/thresh_banner.png',
    imageChmpIcn: 'assets/images/thresh_icon.png',
    imageChmp3D: 'assets/images/thresh_3d.png',
    imageClasses: 'assets/images/support_legacy.png',
    imageLegacy: [
      'assets/images/support_legacy.png',
      'assets/images/tank_icon.png'
    ],
    imagePosition: 'assets/images/support_position.png',
    imageResource: 'assets/images/mana_icon.png',
    imageRange: 'assets/images/ranged_icon.png',
  ),
  Championss(
    name: 'Xerath',
    title: 'The Magus Ascendant',
    release: '2011-10-05',
    lastUpdate: 'V14.9',
    classes: 'Artillery',
    legacy: ['Mage', 'Support'],
    position: 'Support',
    resource: 'Mana',
    rangeType: 'Ranged',
    adaptiveType: 'Magic',
    storePriceBE: '1350',
    storePriceRP: '585',
    imageChmp: 'assets/images/xerath_banner.png',
    imageChmpIcn: 'assets/images/xerath_icon.png',
    imageChmp3D: 'assets/images/xerath_3d.png',
    imageClasses: 'assets/images/mage_icon.png',
    imageLegacy: [
      'assets/images/mage_icon.png',
      'assets/images/support_legacy.png'
    ],
    imagePosition: 'assets/images/support_position.png',
    imageResource: 'assets/images/mana_icon.png',
    imageRange: 'assets/images/ranged_icon.png',
  ),
  Championss(
    name: 'Yasuo',
    title: 'The Unforgiven',
    release: '2013-12-13',
    lastUpdate: 'V14.15',
    classes: 'Skirmisher',
    legacy: ['Fighter', 'Assassin'],
    position: 'Top',
    resource: 'Flow',
    rangeType: 'Melee',
    adaptiveType: 'Physical',
    storePriceBE: '1350',
    storePriceRP: '585',
    imageChmp: 'assets/images/yanto_banner.png',
    imageChmpIcn: 'assets/images/yanto_icon.png',
    imageChmp3D: 'assets/images/yanto_3d.png',
    imageClasses: 'assets/images/assassin_icon.png',
    imageLegacy: [
      'assets/images/fighter_icon.png',
      'assets/images/assassin_icon.png'
    ],
    imagePosition: 'assets/images/top_icon.png',
    imageResource: 'assets/images/flow_icon.png',
    imageRange: 'assets/images/melee_icon.png',
  ),
  Championss(
    name: 'Renata Glasc',
    title: 'The Chem-Baroness',
    release: '2022-02-17',
    lastUpdate: 'V14.7',
    classes: 'Enchanter',
    legacy: ['Support', 'Mage'],
    position: 'Support',
    resource: 'Mana',
    rangeType: 'Ranged',
    adaptiveType: 'Magic',
    storePriceBE: '4800',
    storePriceRP: '880',
    imageChmp: 'assets/images/renata_glasc_banner.png',
    imageChmpIcn: 'assets/images/renata_glasc_icon.png',
    imageChmp3D: 'assets/images/renata_glasc_3d.png',
    imageClasses: 'assets/images/assassin_icon.png',
    imageLegacy: [
      'assets/images/support_legacy.png',
      'assets/images/mage_icon.png'
    ],
    imagePosition: 'assets/images/support_position.png',
    imageResource: 'assets/images/mana_icon.png',
    imageRange: 'assets/images/ranged_icon.png',
  ),
  Championss(
    name: "Rek'Sai",
    title: 'The Void Burrower',
    release: '2014-12-11',
    lastUpdate: 'V14.12',
    classes: 'Diver',
    legacy: ['Fighter', 'Tank'],
    position: 'Jungle',
    resource: 'Rage',
    rangeType: 'Melee',
    adaptiveType: 'Physical',
    storePriceBE: '4800',
    storePriceRP: '880',
    imageChmp: 'assets/images/reksai_banner.png',
    imageChmpIcn: 'assets/images/reksai_icon.png',
    imageChmp3D: 'assets/images/reksai_3d.png',
    imageClasses: 'assets/images/fighter_icon.png',
    imageLegacy: [
      'assets/images/fighter_icon.png',
      'assets/images/tank_icon.png'
    ],
    imagePosition: 'assets/images/jungle_icon.png',
    imageResource: 'assets/images/rage_icon.png',
    imageRange: 'assets/images/melee_icon.png',
  ),
  Championss(
    name: 'Kassadin',
    title: 'The Void Walker',
    release: '2009-08-07',
    lastUpdate: 'V14.10',
    classes: 'Assassin',
    legacy: ['Assassin', 'Mage'],
    position: 'Middle',
    resource: 'Mana',
    rangeType: 'Melee',
    adaptiveType: 'Magic',
    storePriceBE: '3150',
    storePriceRP: '790',
    imageChmp: 'assets/images/kassadin_banner.png',
    imageChmpIcn: 'assets/images/kassadin_icon.png',
    imageChmp3D: 'assets/images/kassadin_3d.png',
    imageClasses: 'assets/images/assassin_icon.png',
    imageLegacy: [
      'assets/images/assassin_icon.png',
      'assets/images/mage_icon.png'
    ],
    imagePosition: 'assets/images/mid_icon.png',
    imageResource: 'assets/images/mana_icon.png',
    imageRange: 'assets/images/melee_icon.png',
  ),
  Championss(
    name: 'Jax',
    title: 'Grandmaster At Arms',
    release: '2009-02-21',
    lastUpdate: 'V14.14',
    classes: 'Skirmisher',
    legacy: ['Fighter', 'Assassin'],
    position: 'Jungle',
    resource: 'Mana',
    rangeType: 'Melee',
    adaptiveType: 'Physical',
    storePriceBE: '1350',
    storePriceRP: '585',
    imageChmp: 'assets/images/jax_banner.png',
    imageChmpIcn: 'assets/images/jax_icon.png',
    imageChmp3D: 'assets/images/jax_3d.png',
    imageClasses: 'assets/images/assassin_icon.png',
    imageLegacy: [
      'assets/images/fighter_icon.png',
      'assets/images/assassin_icon.png',
    ],
    imagePosition: 'assets/images/jungle_icon.png',
    imageResource: 'assets/images/mana_icon.png',
    imageRange: 'assets/images/melee_icon.png',
  ),
  Championss(
    name: 'Gwen',
    title: 'The Hallowed Seamstress',
    release: '2021-04-15',
    lastUpdate: 'V14.9',
    classes: 'Skirmisher',
    legacy: ['Fighter', 'Assassin'],
    position: 'Top',
    resource: 'Mana',
    rangeType: 'Melee',
    adaptiveType: 'Magic',
    storePriceBE: '4800',
    storePriceRP: '880',
    imageChmp: 'assets/images/gwen_banner.png',
    imageChmpIcn: 'assets/images/gwen_icon.png',
    imageChmp3D: 'assets/images/gwen_3d.png',
    imageClasses: 'assets/images/assassin_icon.png',
    imageLegacy: [
      'assets/images/fighter_icon.png',
      'assets/images/assassin_icon.png',
    ],
    imagePosition: 'assets/images/top_icon.png',
    imageResource: 'assets/images/mana_icon.png',
    imageRange: 'assets/images/melee_icon.png',
  ),
  Championss(
    name: 'Zeri',
    title: 'The Spark Of Zaun',
    release: '2022-01-20',
    lastUpdate: 'V14.8',
    classes: 'Marksman',
    legacy: ['Marksman', 'Marksman'],
    position: 'Bottom',
    resource: 'Mana',
    rangeType: 'Ranged',
    adaptiveType: 'Physical',
    storePriceBE: '4800',
    storePriceRP: '880',
    imageChmp: 'assets/images/zeri_banner.png',
    imageChmpIcn: 'assets/images/zeri_icon.png',
    imageChmp3D: 'assets/images/zeri_3d.png',
    imageClasses: 'assets/images/marksman_icon.png',
    imageLegacy: [
      'assets/images/marksman_icon.png',
      'assets/images/marksman_icon.png',
    ],
    imagePosition: 'assets/images/bottom_icon.png',
    imageResource: 'assets/images/mana_icon.png',
    imageRange: 'assets/images/ranged_icon.png',
  ),
];
